window.intellectualHistorySources = [
  { cluster: "media ecology", year: "1938", title: "Experience and Education", author: "John Dewey", role: "Frames learning as experience, continuity, and educative difficulty.", bridge: "Supports the distinction between productive and unproductive educational difficulty.", status: "Verify bibliography" },
  { cluster: "media ecology", year: "1964", title: "Understanding Media", author: "Marshall McLuhan", role: "Provides the media-ecological claim that media reshape perception, scale, and social organization.", bridge: "Helps explain GenAI as a condition of schooling, not merely a tool inside schooling.", status: "Local source folder" },
  { cluster: "media ecology", year: "1982", title: "Orality and Literacy", author: "Walter J. Ong", role: "Supplies the oral/literate media ecology that the qualifying paper extends toward algorithmic secondary orality.", bridge: "A core theoretical ancestor for tertiary algorithmicity.", status: "Core source" },
  { cluster: "media ecology", year: "1992", title: "Technopoly", author: "Neil Postman", role: "Names how technological systems reorganize cultural judgment and institutional priorities.", bridge: "Supports the governance and school-policy dimension of the dissertation.", status: "Verify bibliography" },
  { cluster: "learning science", year: "1978", title: "Mind in Society", author: "Lev Vygotsky", role: "Anchors mediation, social learning, and the role of tools in cognition.", bridge: "Useful for explaining why AI-mediated language changes the learning situation.", status: "Verify bibliography" },
  { cluster: "learning science", year: "1980", title: "Mindstorms", author: "Seymour Papert", role: "Offers a constructionist account of computers, learning, and student authorship.", bridge: "Creates a contrast between learner construction and AI-assisted bypass.", status: "Local source folder" },
  { cluster: "learning science", year: "1988", title: "Cognitive load during problem solving", author: "John Sweller", role: "Clarifies why some difficulty aids learning and some overloads working memory.", bridge: "Helps discipline the productive/exclusionary friction distinction.", status: "Verify bibliography" },
  { cluster: "learning science", year: "1994", title: "Memory and metamemory considerations in the training of human beings", author: "Robert A. Bjork", role: "Introduces desirable difficulties as a learning-science anchor.", bridge: "Supports friction as a carefully designed condition rather than mere hardship.", status: "Verify bibliography" },
  { cluster: "learning science", year: "2008", title: "Productive Failure", author: "Manu Kapur", role: "Shows how structured struggle can prepare learners for deeper conceptual understanding.", bridge: "Provides a central empirical cousin to pedagogical friction.", status: "Verify bibliography" },
  { cluster: "algorithm studies", year: "2017", title: "Thinking critically about and researching algorithms", author: "Rob Kitchin", role: "Frames algorithms as social, technical, and epistemic arrangements that need critical study.", bridge: "Supports the move from tool use to algorithmic conditions.", status: "Local source folder" },
  { cluster: "algorithm studies", year: "2018", title: "If...Then: Algorithmic Power and Politics", author: "Taina Bucher", role: "Helps locate algorithmic systems within power, perception, and social life.", bridge: "Strengthens the institutional and governance strand.", status: "Local source folder" },
  { cluster: "media ecology", year: "2010", title: "Taking Care of Youth and the Generations", author: "Bernard Stiegler", role: "Connects technology, attention, formation, and generational responsibility.", bridge: "Supports the dissertation's concern with schooling, care, and attention under technical systems.", status: "Local source folder" },
  { cluster: "ai education", year: "2020", title: "GPT-3: Its Nature, Scope, Limits, and Consequences", author: "Luciano Floridi and Massimo Chiriatti", role: "Provides a philosophical and technical account of large language model limits.", bridge: "Useful for separating fluent production from understanding.", status: "Verify bibliography" },
  { cluster: "ai education", year: "2021", title: "On the Dangers of Stochastic Parrots", author: "Emily M. Bender, Timnit Gebru, Angelina McMillan-Major, and Shmargaret Shmitchell", role: "Names risks around language models, scale, harms, and meaning.", bridge: "Supports caution around rhetorical fluency and synthetic text.", status: "Verify bibliography" },
  { cluster: "methods", year: "2018", title: "Designing and Conducting Mixed Methods Research", author: "John W. Creswell and Vicki L. Plano Clark", role: "Methods anchor for convergent mixed methods, integration, and joint displays.", bridge: "Supports the QUAL + quan design and meta-inference language.", status: "Verify methods citation" },
  { cluster: "methods", year: "2009/2016", title: "Constructivist case study methodology for educational research", author: "Sharan B. Merriam", role: "Primary case study methodology anchor for constructivist educational inquiry.", bridge: "Centers the study as particularistic, descriptive, and heuristic while preserving a clearly bounded educational case.", status: "Primary methods anchor" }
];
